### ISSUE TITLE
Add support for metadata like getTables

### ISSUE THREAD

**Issue by Horcrux7** [panchmp/sqlsheet#15]
We receive an exception with DatabaseMetaData.getTables

java.lang.UnsupportedOperationException: Not supported yet.
    at net.pcal.sqlsheet.XlsDatabaseMetaData.getTables(XlsDatabaseMetaData.java:504)

**Comment by manticore-projects** [comment]
Solved by PR #35, can be closed.

**Comment by Horcrux7** [comment]
Mal den Excel Treiber anschauen

Am Di., 27. Okt. 2020 um 08:32 Uhr schrieb manticore-projects <
notifications@github.com>:
