### ISSUE TITLE
Missing artifact net.sf:jsqlparser:jar:0.8.0

### ISSUE THREAD

**Issue by klaushauschild1984** [panchmp/sqlsheet#23]
Mail from Stephen Rufle:

I am one of the maintainers of
https://github.com/AgileTestingFramework/atf-toolbox-java

I use the 6.5 version of sqlsheet
<dependency>
    <groupId>com.google.code.sqlsheet</groupId>
    <artifactId>sqlsheet</artifactId>
    <version>6.5</version>
</dependency>	

but I am getting this error when I build, which seems to be a dependency of sqlsheet

Missing artifact net.sf:jsqlparser:jar:0.8.0	pom.xml	/atf-toolbox	line 1	Maven Dependency Problem

I see in your project you have upgraded to a later version jsqlparser
https://github.com/panchmp/sqlsheet

I would like to know if you could publish a new version. I can help publish a new version if that would help you. 

Stephen P Rufle

**Comment by panchmp** [comment]
Hi!

I am add you to collaborator. 
Fill free add new changes and publish new  releases

Regards
Micahel

**Comment by klaushauschild1984** [comment]
The problem itself is resolved. But I have some problems releasing a new version based on the current state. Maven-release-plugin just hangs when tagging the version to release.

**Comment by srufle** [comment]
k, I have only ever published my own project . Can I try and clone this project and follow http://central.sonatype.org/pages/ossrh-guide.html using my own signing key? Will prob happen over the weekend.

**Comment by klaushauschild1984** [comment]
Great!

**Comment by srufle** [comment]
I logged into https://oss.sonatype.org/ and looked for sqlsheet. A 6.6-SNAPSHOT has already been published in 2013.  
When I 
`mvn clean install`
I got a warning
```
[WARNING] Javadoc Warnings
[WARNING] C:\code\src\github.com\panchmp\sqlsheet\src\main\java\net\pcal\sqlsheet\XlsResultSet.java:522: warning: no description for @param
[WARNING] * @param jdbcColumn
[WARNING] ^
```
I forked and fixed the issue.  Tomorrow I will see what I can get working from this doc. You may have to do the steps in this doc since you prob have all the correct permissions. Your issue from above may have been caused by the previous 6.6-SNAPSHOT version. Maybe bump to 6.7 and see how it goes :)

http://central.sonatype.org/pages/apache-maven.html

**Comment by srufle** [comment]
You will have to publish the new version, since I do not have the correct permissions.

**Comment by klaushauschild1984** [comment]
I havn't permissions, too. Who can help?

**Comment by srufle** [comment]
@panchmp How do we publish a release? 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project sqlsheet: Unable to commit files
[ERROR] Provider message:
[ERROR] The git-push command failed.
[ERROR] Command output:
[ERROR] remote: Permission to panchmp/sqlsheet.git denied to srufle.
[ERROR] fatal: unable to access 'https://github.com/panchmp/sqlsheet/': The requested URL returned error: 403
[ERROR] -> [Help 1]
[ERROR]
```

**Comment by srufle** [comment]
@panchmp I looked at one of my personal repo's to see how I would allow people to push back. It might require us to send you our [Deploy Keys](https://developer.github.com/guides/managing-deploy-keys/#deploy-keys) for I or @klaushauschild1984 to publish a new release.

**Comment by srufle** [comment]
Bump

**Comment by panchmp** [comment]
Done
