### ISSUE TITLE
XLS in JAR as Resource

### ISSUE THREAD

**Issue by leojhartiv** [panchmp/sqlsheet#29]
It doesn't appear that there's any way to access an XLS file that's embedded in a JAR as a resource.  Is that accurate?

I tried doing something like this: "jdbc:xls:resource:test.xlsx"

But got this error message:

"Caused by: java.net.MalformedURLException: unknown protocol: resource"

**Comment by klaushauschild1984** [comment]
No, currently not. Tge drivers implementation assumes that the url point to a fiel stored in the file system.
But load as a resource from classpath or an URL is quiet a nice feature request. For tge classpath variant there could be some guessing be implemented. So you provide the path and the driver checks the classpath and the file system.
