### ISSUE TITLE
Select * from sheets[0]

### ISSUE THREAD

**Issue by hakimda** [panchmp/sqlsheet#40]
Hi,
Greag tool with scriptella.
I'm unable to : select * from "sheet accessed by index".I have only one sheet in the workbook but don't know the name of the sheet.
Thanks

**Comment by manticore-projects** [comment]
Greetings!

Sorry for being a bit late. Access by sheet index works now, e. g.

```sql
select * from "sheet[0]"
```

Please note:
- you need to use quotes (either double quotes `"` or back-ticks)
- index starts at 0 (not 1)
